name: make-release-artifacts

on:
  release:
    types: [ prereleased ]
    branches: [ main ]

jobs:
  generate-2d-render:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    steps:
    - uses: actions/checkout@v2

    - name: Run exporter
      run: |
        make -C pcb_main help

  generate-3d-render:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    steps:
    - uses: actions/checkout@v2

    - name: Run eporter
      run: |
        make -C pcb_main help
  add-labels-for-pins:
    runs-on: ubuntu-latest
    container: python:buster
    steps:
    - uses: actions/checkout@v2

    - name: Install tool
      run: |
        pip install pinout
    - name: Export the image
      run: |
        py -m pinout.manager --export pinout_diagram.py diagram.svg
  generate-gerbers:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
